### ISSUE TITLE
Ability to Send Invite to the Same Credential After Sign-In

### ISSUE THREAD

**Issue by Gloriean** [rotimi-best/classroomio#94] opened 2023-12-09 18:21 UTC
### Issue Description

After signing in, users can send an invite to the same credential, which should be restricted to avoid potential duplicate entries.
Allowing invitees to use the same credential can lead to duplicate entries and potential data inconsistencies.

<img width="1667" alt="Screenshot 2023-12-09 at 19 19 43" src="https://github.com/rotimi-best/classroomio/assets/99972504/0bc6eaab-b5fc-4a26-a310-ceb749a7987c">

### Steps to Reproduce

1. Log in to the application.
2. Navigate to the "Settings" feature.
3. Navigate to the invite section.
4. Send an invite to a specific user by entering their same credential that was used to login.

### Expected Behavior

Users should be restricted from sending an invite to the same credential after signing in, and an appropriate error message should be displayed.

### Current Behavior

Users are able to send an invite to the same credential after signing in, without receiving any error message.

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rotimi-best** [comment] 2023-12-09 18:53
Hi @Gloriean, is this not a duplicate of https://github.com/rotimi-best/classroomio/issues/88

**Comment by rotimi-best** [comment] 2023-12-11 09:33
Closing as duplicate of #88

**Closed by rotimi-best** 2023-12-11 09:33 UTC
Labels: bug
